//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsportDK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spillere
    {
        public int ID { get; set; }
        public string forNavn { get; set; }
        public string efterNavn { get; set; }
        public string rang { get; set; }
        public string telefon { get; set; }
        public string turneringsType { get; set; }
    }
}
